const nodemailer = require("nodemailer");

async function sendMail({ from, to, subject, text, html }) {
  console.log("first point");
  let transporter = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "5869502061d88e", //generated by Mailtrap
      pass: "3e4d33e4f149c2" //generated by Mailtrap
    }
  });
  transporter.verify(function(error, success) {
    if (error) {
         console.log(error);
    } else {
         console.log('Server is ready to take our messages');
    }
  });
  console.log("second point");

  let info = await transporter.sendMail({
    from: `Spreader<${from}>`,
    to: to,
    subject: subject,
    text: text,
    html: html,
  }).catch(err => {
    console.log("Err: ", err);
  });
  console.log("third point");

  console.log(info);
}

module.exports = sendMail;
